### ISSUE TITLE
Uncaught Error: Class 'League\Flysystem\Adapter\Local' not found

### ISSUE THREAD

**Issue by ErminMerdanovic** [backup-manager/backup-manager#188]
If tried to install the Backup Manager but on execution i receive an error.

PHP: 7.4.26
I also ran Composer as required

`Fatal error: Uncaught Error: Class 'League\Flysystem\Adapter\Local' not found in C:\xampp\htdocs\Backup\vendor\backup-manager\backup-manager\src\Filesystems\LocalFilesystem.php:28 Stack trace: #0 C:\xampp\htdocs\Backup\vendor\backup-manager\backup-manager\src\Filesystems\FilesystemProvider.php(47): BackupManager\Filesystems\LocalFilesystem->get(Array) #1 C:\xampp\htdocs\Backup\vendor\backup-manager\backup-manager\src\Procedures\BackupProcedure.php(32): BackupManager\Filesystems\FilesystemProvider->get('local') #2 C:\xampp\htdocs\Backup\standalone\backup.php(10): BackupManager\Procedures\BackupProcedure->run('production', Array, 'gzip') #3 {main} thrown in C:\xampp\htdocs\Backup\vendor\backup-manager\backup-manager\src\Filesystems\LocalFilesystem.php on line 28`

**Comment by Strentz-Paul** [comment]
@Nyholm 
The problem is from the file src/Filesystems/LocalFilesystem.php
I fixed it in local with this use ```use League\Flysystem\Local\LocalFilesystemAdapter as Local;``` Should i open a PR for this?

**Comment by Nyholm** [comment]
Hm.. I would much rather do #185 and make a new major. That would properly keep compatibility with Flysystem

**Comment by henry-ht** [comment]
a fast solucion here.
run this after composer install or run on custom command.

this code replace default import

```
$pathToFile = "vendor\backup-manager\backup-manager\src\Filesystems\LocalFilesystem.php";
$originalText = "use League\Flysystem\Adapter\Local;";
$textReplace = "use League\Flysystem\Local\LocalFilesystemAdapter as Local;";

$fileChange = file_get_contents(__DIR__.'\\..\\..\\'.$pathToFile);
$textContent = str_replace($originalText, $textReplace, $fileChange);
file_put_contents($pathToFile, $textContent);
```
