### ISSUE TITLE
ProcessTimeout

### ISSUE THREAD

**Issue by lflaszlo** [backup-manager/backup-manager#80]
Hi,
I have scheduled a job to backup my database.
Since July 1st, the database has grown and the backup process timeout.
Can you help me, have you an idea ? 

```
'Symfony\Component\Process\Exception\ProcessTimedOutException' with message 'The process "PGPASSWORD='******' pg_dump --host='localhost' --port='5432' --username='*********' '*********' -f '/var/opt/flat/application/api/55a6e5f2c4253'" exceeded the timeout of 60 seconds.' in /opt/application/api/G02R11C02/vendor/symfony/process/Symfony/Component/Process/Process.php:1219 

Stack trace: #0 /opt/application/api/G02R11C02/vendor/symfony/process/Symfony/Component/Process/Process.php(357): Symfony\Component\Process\Process->checkTimeout() 
#1 /opt/application/api/G02R11C02/vendor/symfony/process/Symfony/Component/Process/Process.php(206): Symfony\Component\Process\Process->wait() 
#2 /opt/application/api/G02R11C02/vendor/heybigname/backup-manager/src/ShellProcessing/ShellProcessor.php(36): Symfony\Component\Process\Process->run() #3 /opt/application/api/G02R11C02/vendor/heybigname/backup-manager/src/Tasks/Database/DumpDatabase.php(43): BigName\BackupManager\ShellProcessing\ShellProcessor->process('PGPASSWORD='*****...') 
#4 /opt/application/api/G02R11C02/vendor/heybigname/backup-manager/src/Procedures/Sequence.php(31): BigName\BackupManager\Tasks\Database\DumpDatabase->execute() 
#5 /opt/application/api/G02R11C02/vendor/heybigname/backup-manager/src/Procedures/BackupProcedure.php(67): BigName\BackupManager\Procedures\Sequence->execute() 
#6 /opt/application/api/G02R11C02/vendor/heybigname/backup-manager/src/Integrations/Laravel/DbBackupCommand.php(94): BigName\BackupManager\Procedures\BackupProcedure->run('pgsql', 'local', 'backup_bdd/ppro...', 'gzip') 
#7 /opt/application/api/G02R11C02/vendor/laravel/framework/src/Illuminate/Console/Command.php(112): BigName\BackupManager\Integrations\Laravel\DbBackupCommand->fire() 
#8 /opt/application/api/G02R11C02/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(253): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 
#9 /opt/application/api/G02R11C02/vendor/laravel/framework/src/Illuminate/Console/Command.php(100): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 
#10 /opt/application/api/G02R11C02/vendor/laravel/framework/src/Illuminate/Console/Command.php(128): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 
#11 /opt/application/api/G02R11C02/app/commands/sch_jobs/Backup.php(60): Illuminate\Console\Command->call('db:backup', Array) 
#12 /opt/application/api/G02R11C02/vendor/laravel/framework/src/Illuminate/Console/Command.php(112): Backup->fire() 
#13 /opt/application/api/G02R11C02/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(253): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 
#14 /opt/application/api/G02R11C02/vendor/laravel/framework/src/Illuminate/Console/Command.php(100): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 
#15 /opt/application/api/G02R11C02/vendor/symfony/console/Symfony/Component/Console/Application.php(889): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 
#16 /opt/application/api/G02R11C02/vendor/symfony/console/Symfony/Component/Console/Application.php(193): Symfony\Component\Console\Application->doRunCommand(Object(Backup), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 
#17 /opt/application/api/G02R11C02/vendor/symfony/console/Symfony/Component/Console/Application.php(124): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 
#18 /opt/application/api/G02R11C02/artisan(59): Symfony\Component\Console\Application->run() 
#19 {main}
```

**Comment by lflaszlo** [comment]
up ?
